# Attention: This file is for development purpose only and can be ignored.

# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.ha_data_editor: debug
