update_device:
  description: Updates a device description in the device registry.
  fields:
    device_id:
      description: The id of the device to update.
      example: "1234abcd"
      required: true
      selector:
        device:

    area_id:
      description: The new area to assign to the device.
      example: "living_room"
      required: true
      selector:
        area:
